version: '3.8'

services:
  db:
    container_name: db
    restart: always
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=muse
    networks:
      - db_network

  api:
    container_name: api
    restart: always
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/api
      - /api/node_modules'
    depends_on:
      - db
    networks:
      - web_network
      - db_network

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge

volumes:
  postgres-data:
