import {
  createAlbumsTracksController,
  getAlbumsController,
  getAlbumsTracksController,
  getSeveralAlbumsController,
  updateAlbumDetailsController,
  uploadAlbumsImagesController,
  removeAlbumsTracksController,
  removeAlbumsImagesController,
} from './albums';
import {
  createArtistsAlbumsController,
  getArtistsAlbumsController,
  getArtistsController,
  getArtistsTracksController,
  getSeveralArtistsController,
} from './artists';
import { login, register } from './authentication';
import {
  getCurrentUsersAlbumsController,
  getCurrentUsersPlaylistsController,
  getCurrentUsersProfileController,
  getCurrentUsersTracksController,
} from './me';
import {
  addPlaylistsTracksController,
  getPlaylistController,
  getPlaylistsTracksController,
  getSeveralPlaylistsController,
  removePlaylistsTracksController,
  updatePlaylistDetailsController,
  uploadPlaylistsImagesController,
  removePlaylistsImagesController,
} from './playlists';
import {
  getSeveralTracksController,
  getTracksController,
  updateTrackController,
} from './tracks';
import {
  createUsersPlaylistController,
  getSeveralUsersController,
  getUsersPlaylistsController,
  getUsersProfileController,
  updateUsersProfileController,
  uploadUsersImagesController,
} from './users';
export {
  removePlaylistsImagesController,
  removeAlbumsImagesController,
  removeAlbumsTracksController,
  uploadAlbumsImagesController,
  addPlaylistsTracksController,
  createAlbumsTracksController,
  createArtistsAlbumsController,
  createUsersPlaylistController,
  getAlbumsController,
  getAlbumsTracksController,
  getArtistsAlbumsController,
  getArtistsController,
  getArtistsTracksController,
  getCurrentUsersAlbumsController,
  getCurrentUsersPlaylistsController,
  getCurrentUsersProfileController,
  getCurrentUsersTracksController,
  getPlaylistController,
  getPlaylistsTracksController,
  getSeveralAlbumsController,
  getSeveralArtistsController,
  getSeveralPlaylistsController,
  getSeveralTracksController,
  getSeveralUsersController,
  getTracksController,
  getUsersPlaylistsController,
  getUsersProfileController,
  login,
  register,
  removePlaylistsTracksController,
  updateAlbumDetailsController,
  updatePlaylistDetailsController,
  updateTrackController,
  updateUsersProfileController,
  uploadPlaylistsImagesController,
  uploadUsersImagesController,
};
