import {
  createAlbumsTracksController,
  getAlbumsController,
  getAlbumsTracksController,
  getSeveralAlbumsController,
  removeAlbumsImagesController,
  removeAlbumsTracksController,
  updateAlbumDetailsController,
  uploadAlbumsImagesController,
  addAlbumsGenresController,
  removeAlbumsGenresController,
  addAlbumsArtistsController,
  removeAlbumsArtistsController,
} from './albums';
import {
  createArtistsAlbumsController,
  getArtistsAlbumsController,
  getArtistsController,
  getArtistsTracksController,
  getSeveralArtistsController,
  removeArtistsAlbumsController,
} from './artists';
import { login, refresh, register } from './authentication';
import {
  createCategoriesController,
  deleteCategoriesController,
  deleteSeveralCategoriesController,
  getCategoriesController,
  getSeveralCategoriesController,
  updateCategoriesController,
} from './categories';
import {
  createGenresController,
  deleteGenresController,
  deleteSeveralGenresController,
  getGenresController,
  getSeveralGenresController,
  updateGenresController,
} from './genres';
import {
  getCurrentUsersAlbumsController,
  getCurrentUsersPlaylistsController,
  getCurrentUsersProfileController,
  getCurrentUsersTracksController,
} from './me';
import {
  addPlaylistsTracksController,
  getPlaylistController,
  getPlaylistsTracksController,
  getSeveralPlaylistsController,
  removePlaylistsImagesController,
  removePlaylistsTracksController,
  updatePlaylistDetailsController,
  uploadPlaylistsImagesController,
} from './playlists';
import {
  getSeveralTracksController,
  getTracksController,
  updateTrackController,
  addTracksArtistsController,
  removeTracksArtistsController,
} from './tracks';
import {
  createUsersPlaylistController,
  getSeveralUsersController,
  getUsersPlaylistsController,
  getUsersProfileController,
  updateUsersProfileController,
  uploadUsersImagesController,
  removeUsersPlaylistsController,
  becomeArtistController,
} from './users';
export {
  becomeArtistController,
  removeUsersPlaylistsController,
  addTracksArtistsController,
  removeTracksArtistsController,
  removeArtistsAlbumsController,
  addAlbumsArtistsController,
  removeAlbumsArtistsController,
  removeAlbumsGenresController,
  addAlbumsGenresController,
  addPlaylistsTracksController,
  createAlbumsTracksController,
  createArtistsAlbumsController,
  createCategoriesController,
  createGenresController,
  createUsersPlaylistController,
  deleteCategoriesController,
  deleteGenresController,
  deleteSeveralCategoriesController,
  deleteSeveralGenresController,
  getAlbumsController,
  getAlbumsTracksController,
  getArtistsAlbumsController,
  getArtistsController,
  getArtistsTracksController,
  getCategoriesController,
  getCurrentUsersAlbumsController,
  getCurrentUsersPlaylistsController,
  getCurrentUsersProfileController,
  getCurrentUsersTracksController,
  getGenresController,
  getPlaylistController,
  getPlaylistsTracksController,
  getSeveralAlbumsController,
  getSeveralArtistsController,
  getSeveralCategoriesController,
  getSeveralGenresController,
  getSeveralPlaylistsController,
  getSeveralTracksController,
  getSeveralUsersController,
  getTracksController,
  getUsersPlaylistsController,
  getUsersProfileController,
  login,
  refresh,
  register,
  removeAlbumsImagesController,
  removeAlbumsTracksController,
  removePlaylistsImagesController,
  removePlaylistsTracksController,
  updateAlbumDetailsController,
  updateCategoriesController,
  updateGenresController,
  updatePlaylistDetailsController,
  updateTrackController,
  updateUsersProfileController,
  uploadAlbumsImagesController,
  uploadPlaylistsImagesController,
  uploadUsersImagesController,
};
