version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: muse
    networks:
      apinetwork:
        ipv4_address: 172.50.0.10

volumes:
  postgres-data:

networks:
  apinetwork:
    ipam:
      config:
        - subnet: 172.50.0.0/16
