import {
  createAlbumsTracksModel,
  getAlbumsModel,
  getAlbumsTracksModel,
  getSeveralAlbumsModel,
  removeAlbumsImagesModel,
  removeAlbumsTracksModel,
  updateAlbumDetailsModel,
  uploadAlbumsImagesModel,
  addAlbumsGenresModel,
  removeAlbumsGenresModel,
  addAlbumsArtistsModel,
  removeAlbumsArtistsModel,
} from './albums';
import {
  createArtistsAlbumsModel,
  getArtistsAlbumsModel,
  getArtistsModel,
  getArtistsTracksModel,
  getSeveralArtistsModel,
  removeArtistsAlbumsModel,
} from './artists';
import {
  createCategoriesModel,
  deleteCategoriesModel,
  deleteSeveralCategoriesModel,
  getCategoriesModel,
  getSeveralCategoriesModel,
  updateCategoriesModel,
} from './categories';
import {
  createGenresModel,
  deleteGenresModel,
  deleteSeveralGenresModel,
  getGenresModel,
  getSeveralGenresModel,
  updateGenresModel,
} from './genres';
import {
  getCurrentUsersAlbumsModel,
  getCurrentUsersPlaylistsModel,
  getCurrentUsersProfileModel,
  getCurrentUsersTracksModel,
} from './me';
import {
  addPlaylistsTracksModel,
  getPlaylistModel,
  getPlaylistsTracksModel,
  getSeveralPlaylistsModel,
  removePlaylistsImagesModel,
  removePlaylistsTracksModel,
  updatePlaylistDetailsModel,
  uploadPlaylistsImagesModel,
} from './playlists';
import {
  getSeveralTracksModel,
  getTracksModel,
  updateTrackDetailsModel,
  addTracksArtistsModel,
  removeTracksArtistsModel,
} from './tracks';
import {
  createUserModel,
  createUsersPlaylistModel,
  getSeveralUsersModel,
  getUserByEmailModel,
  getUsersPlaylistsModel,
  getUsersProfileModel,
  updateUsersProfileModel,
  uploadUsersImagesModel,
  removeUsersPlaylistsModel,
  becomeArtistModel,
} from './users';

export {
  becomeArtistModel,
  removeUsersPlaylistsModel,
  addTracksArtistsModel,
  removeTracksArtistsModel,
  removeArtistsAlbumsModel,
  addAlbumsArtistsModel,
  removeAlbumsArtistsModel,
  removeAlbumsGenresModel,
  addAlbumsGenresModel,
  addPlaylistsTracksModel,
  createAlbumsTracksModel,
  createArtistsAlbumsModel,
  createCategoriesModel,
  createGenresModel,
  createUserModel,
  createUsersPlaylistModel,
  deleteCategoriesModel,
  deleteGenresModel,
  deleteSeveralCategoriesModel,
  deleteSeveralGenresModel,
  getAlbumsModel,
  getAlbumsTracksModel,
  getArtistsAlbumsModel,
  getArtistsModel,
  getArtistsTracksModel,
  getCategoriesModel,
  getCurrentUsersAlbumsModel,
  getCurrentUsersPlaylistsModel,
  getCurrentUsersProfileModel,
  getCurrentUsersTracksModel,
  getGenresModel,
  getPlaylistModel,
  getPlaylistsTracksModel,
  getSeveralAlbumsModel,
  getSeveralArtistsModel,
  getSeveralCategoriesModel,
  getSeveralGenresModel,
  getSeveralPlaylistsModel,
  getSeveralTracksModel,
  getSeveralUsersModel,
  getTracksModel,
  getUserByEmailModel,
  getUsersPlaylistsModel,
  getUsersProfileModel,
  removeAlbumsImagesModel,
  removeAlbumsTracksModel,
  removePlaylistsImagesModel,
  removePlaylistsTracksModel,
  updateAlbumDetailsModel,
  updateCategoriesModel,
  updateGenresModel,
  updatePlaylistDetailsModel,
  updateTrackDetailsModel,
  updateUsersProfileModel,
  uploadAlbumsImagesModel,
  uploadPlaylistsImagesModel,
  uploadUsersImagesModel,
};
